### ISSUE TITLE
Add to documentation how to delete "squashed" branches

### ISSUE THREAD

**Issue by koppor** [lzap/git-xcleaner#4]
GitHub allows for squashing commits into one when merging a branch. See https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/incorporating-changes-from-a-pull-request/about-pull-request-merges#squash-and-merge-your-pull-request-commits. Therefore, one cannot simply use `--merged` of git to delete these branches. There needs to be sophisticated functionality for that. See https://stackoverflow.com/q/43489303/873282 for a discussion.

Coming from https://stackoverflow.com/questions/43489303/how-can-i-delete-all-git-branches-which-have-been-squash-and-merge-via-github/66732155?noredirect=1#comment125436192_66732155, there is the claim that this tool can also handle that case. When quickly checking the code (https://github.com/lzap/git-xcleaner/blob/d18df7f66ffc3ffa848dc1cfc685a4aea4fdbeb7/git-xcleaner#L102), this tool at hand relies on `--merged` and does not contain other solutions to detected squash-merged branches.

**Comment by lzap** [comment]
Have you even bothered reading the initial screen? Yes, it offers `--merged` option, that is the first option. Now, the second option already allows heuristic approach of the problem you describe by comparing tips and finding commits with same commit messages: "Delete (rebased) branches with the same commit messages" and there is the third option which uses pruning which also allows solving of the described problem.

I understand the pain, our team enforces fast forward merging for over a decade now. I don't use github and I am aware it modifies the commit message by default if you use squash, so pruning or even manual deletion is the best bet. But option number two works great on our projects where we rebase manually or if you use the rebase option on github.

> When quickly checking the code

And what is the purpose of this? You probably spent more time writing your rant than reading the code which is by the way three pages long. My tool is unique because it is interactive, you can select whatever you want. I've got some forks and stars so I guess it is useful.

Stay safe!
